### ISSUE TITLE
Undefined variable - Empty filename or path ...

### ISSUE THREAD

**Issue by LiNgOtT** [lousson/record#8]
Found undefined variable ($location) in method \Lousson\Record\Builtin\BuiltinRecordManager::determineMimeType in file lousson/record/src/php/Lousson/Record/Builtin/BuiltinRecordManager.php on line 263.

> PHP Warning : Warning: finfo_file() [<a href='function.finfo-file'>function.finfo-file</a>]: Empty filename or path in lousson/record/src/php/Lousson/Record/Builtin/BuiltinRecordManager.php on line 263

    $info = finfo_open(FILEINFO_MIME_TYPE);
    $type = @finfo_file($info, (string) $location)?: null;
    finfo_close($info);

**Comment by djaenecke** [comment]
Bugfix accepted, issue closed
